name: Build and Submit Mobile App

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  build_android:
    name: Build & Submit Android Production
    type: build
    params:
      platform: android
      profile: production
    hooks:
      after_build:
        - type: submit
          params:
            platform: android
            profile: production

  build_ios:
    name: Build & Submit iOS Production
    type: build
    params:
      platform: ios
      profile: production
    hooks:
      after_build:
        - type: submit
          params:
            platform: ios
            profile: production
